name: food_app
description: "A Flutter food classification app with ML integration."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Image handling
  image_picker: ^1.0.7
  image_cropper: ^11.0.0
  camera: ^0.10.5+9
  image: ^4.1.3
  
  # Machine Learning
  tflite_flutter: ^0.11.0
  
  # HTTP requests
  http: ^1.1.0
  
  # State management and utilities
  provider: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/models/
